[build]
  publish = "."

# Helpful security + caching headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://api.qrserver.com https://quickchart.io; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
